### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot round NaN value.

### ISSUE THREAD

**Issue by mildroid** [MoyuruAizawa/Cropify#16]
Hi there. I'm facing this runtime error after choosing image from gallery:
```FATAL EXCEPTION: main
Process: com.yedastegol.storeapp, PID: 15745
java.lang.IllegalArgumentException: Cannot round NaN value.
	at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:1165)
	at io.moyuru.cropify.CropifyKt$cropImage$2.invokeSuspend(Cropify.kt:160)
	at io.moyuru.cropify.CropifyKt$cropImage$2.invoke(Unknown Source:8)
	at io.moyuru.cropify.CropifyKt$cropImage$2.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at io.moyuru.cropify.CropifyKt.cropImage(Cropify.kt:156)
	at io.moyuru.cropify.CropifyKt.access$cropImage(Cropify.kt:1)
	at io.moyuru.cropify.CropifyKt$cropSampledImage$2.invokeSuspend(Cropify.kt:146)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@64945ca, androidx.compose.runtime.BroadcastFrameClock@4b2733b, StandaloneCoroutine{Cancelling}@9b93a58, AndroidUiDispatcher@bb4d7b1]```

**Comment by Pantsoffski** [comment]
Same here...

**Comment by MoyuruAizawa** [comment]
Thanks.
I will fix it.

**Comment by MoyuruAizawa** [comment]
It was probably fixed in 0.3.2.
Tell me the image size If the error occurs again.
